services:
  - type: web
    name: bidcart-frontend
    env: static
    buildCommand: cd client && npm install && npm run build && cp client/build/index.html client/build/404.html
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html